FROM ubuntu-24.04-noble-amd64-valgrind

USER root
RUN apt-get -qq update && apt-get install -y ubuntu-dbgsym-keyring

RUN echo "deb http://ddebs.ubuntu.com noble main restricted universe multiverse" > /etc/apt/sources.list.d/ddebs.list
RUN echo "deb http://ddebs.ubuntu.com noble-updates main restricted universe multiverse" >> /etc/apt/sources.list.d/ddebs.list
RUN perl -pi -e 's/# deb-src/deb-src/;' /etc/apt/sources.list

RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -y install \
    libfreetype6-dbgsym \
    libtiff5-dbgsym \
    libwebpmux3-dbgsym \
    libwebp7-dbgsym \
    libwebpdemux2-dbgsym \
    libwebpmux3-dbgsym \
    libopenjp2-7-dbgsym \
    libharfbuzz0b-dbgsym \
    libfribidi0-dbgsym \
    emacs-nox

RUN cd /usr/src && apt-get source freetype tiff libwebp libopenjp2-7 harfbuzz fribidi

COPY setup.sh /depends/setup.sh
USER pillow
CMD ["/depends/setup.sh"]
